---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatweb-deployment
  namespace: dev
  labels:
     app: tomcatwebapp
     type: front-end
spec:
  template:
    metadata:
     name: tomcatweb-pod
     labels:
        app: tomcatwebapp
        type: front-end
    spec:
      containers:
      - name: tomcatweb
        image: docker4ranjit/loginwebapp:11

  replicas: 2
  selector:
     matchLabels:
        type: front-end
